@echo off
REM DeepCharts auto-start launcher
REM This file is generated by install.ps1 - do not edit manually
REM It uses the registry to find the repo path at runtime

set "DC_REPO="
for /f "tokens=2*" %%A in ('reg query "HKCU\Software\DeepCharts" /v InstallPath 2^>nul') do set "DC_REPO=%%B"
if not defined DC_REPO (
    echo [DeepCharts] InstallPath not found in registry. Run install.ps1 again.
    exit /b 1
)
if not exist "%DC_REPO%\scripts\start-deepcharts.ps1" (
    echo [DeepCharts] start-deepcharts.ps1 not found at %DC_REPO%\scripts\
    exit /b 1
)
powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "%DC_REPO%\scripts\start-deepcharts.ps1" -Background
